	print *,' '
	print *,' '
	print *,'******************************************************'
	print *,'*  Welcome to ESTM 1.1.04                            *'
        print *,'*  estimating latitude dependent surface temperature *' 
	print *,'*  and vegetation fraction                           *' 
	print *,'*  of an (exo) planet                                *' 
	print *,'*  In this version vegetation does not produce       *'
        print *,'*  any kind of feedback                              *'
	print *,'******************************************************'
	print *,' '
	print *,' '
