	print *,' '
	print *,' '
	print *,'******************************************************'
	print *,'*  Welcome to ESTM 1.1.1                             *'
        print *,'*  estimating latitude dependent surface temperature *' 
	print *,'*  of an (exo) planet                                *' 
	print *,'******************************************************'
	print *,' '
	print *,' '
